### ISSUE TITLE
ListBuilder proxy objects don't override "Set" method

### ISSUE THREAD

**Issue by Quantumplation** [TestStack/TestStack.Dossier#35]
The "Set" method is a convenient way to make changes to your builder objects without having to write a different method for every field on your object.  However, when you are working with the ListBuilder proxy objects (the dynamic types which derive from existing builders), they don't override the Set method.  This means that the following code:

```c#
    var customers = 
        CustomerBuilder.CreateListOfSize(10)
            .All().Set(c => c.FirstName, "test");
```

Is not working as expected, and instead has to be 

```c#
    var customers = 
        CustomerBuilder.CreateListOfSize(10)
            .All().With(cb => cb.Set(c => c.FirstName, "test"));
```

Any way we can get the proxy generation to override the Set method as well?

**Comment by Quantumplation** [comment]
(As a side note, I didn't want to open a whole new issue just to ask a question, is there a way to control the initial seed Dossier uses for it's test data, so that we can reproduce a test that failed?)

**Comment by robdmoore** [comment]
Thanks for raising this; creating an issue is fine for asking a question - often other people might have the same question so it's good to have it indexable by Google. Alternatively, feel free to send short-fork questions to me via Twitter (@robdmoore).

You are completely correct - this is an oversight (bug). I actually picked this problem up yesterday and believe a fix is in the version 3 pull request (#34) currently open. We will release that very soon (it's all but ready to drop).

Thanks again.

**Comment by Quantumplation** [comment]
Great to hear!  Hopefully you guys will get your documentation updated along with it? ;)

**Comment by robdmoore** [comment]
Yep - we've already updated the doco :)

--
Rob Moore | Readify Principal Consultant, Technical Specialist (Microsoft Azure) | m +61 400 777 763 | e rob.moore@readify.net | w readify.net

**Comment by robdmoore** [comment]
V3 is now released.

This should be fixed

**Comment by Quantumplation** [comment]
I see you used my name for the updated documentation :P

**Comment by robdmoore** [comment]
I did?

**Comment by Quantumplation** [comment]
Pi Lanningham

**Comment by robdmoore** [comment]
Oh yeah - not sure where that came from - we generally grab those snippets from the test library :)
