### ISSUE TITLE
Ability to specify a Seed value for all random generation

### ISSUE THREAD

**Issue by Quantumplation** [TestStack/TestStack.Dossier#38]
One of the big concerns my coworkers have over using this library is how reproducible the results are: if it randomly generates some data that causes a test to fail, and we can't get it to produce the same data again, we won't be able to effectively debug the issue.

I'm not overly concerned with this, as I don't see that being too frequent of an issue; it seems to me the kinds of data this library fills in are generic enough to not lead to the kinds of bugs that aren't super easy to spot just looking at the code.

How easy would it be to thread a seed value through the randomly generated parts of this library?

**Comment by robdmoore** [comment]
I don't really see the need for this.

The answer to this is understanding equivalence classes and constrained non-determinism.

See the equivalence classes section of my blog post: http://robdmoore.id.au/blog/2015/04/22/announcing-teststack-dossier-library/

Happy to discuss further though if you still see the need.

**Comment by Quantumplation** [comment]
Side note: one of my coworkers is absolutely tickled pink by the existence of "Any.StringMatching(regex)"
