### ISSUE TITLE
new() constraint on TestDataBuilder<,>

### ISSUE THREAD

**Issue by bendetat** [TestStack/TestStack.Dossier#44]
![](http://i.imgur.com/ZnfjM2U.png)

This makes me incredibly sad.

I want to be able to require some values when creating my builder (otherwise my domain invariants will cause my `BuildObject` method to fall over). But I can't use a parameterised constructor because I'm guessing Dossier uses reflection or something? Probably a totally valid reason, but still. Sad.

**Comment by robdmoore** [comment]
Can you specify default values that meet the invariant in your default builder ctor?

That's what I normally do...

**Comment by bendetat** [comment]
That's perfect most of the time but sometimes I don't want to hide too much of the sausage making.

Contrived example. Say I've got a tax calculator that calculates tax on a given product for a given company:

```
class TaxCalculator {
    public TaxCalculator(Company company) {}
    public decimal GetTax(Product product) {}
}
```

`GetTax` calculates tax differently based on the company (is it outside of Australia, is it an NPO, etc). Now I _should_ add `company` to `GetTax` as a parameter, but I can't, maybe because it's not expedient to refactor (it's passed as an instance to hundreds of places that have no concept of the company).

So to test `GetTax` properly (or to use in an integration style test properly) I should be controlling both `product` and `company`. The fact that I can't explicitly make `company` required means that I may not be consuming it properly in my tests and get unexpected (hard to debug) results.

This is an edge case though, there's plenty of workarounds.

**Comment by robdmoore** [comment]
Hmm fair point.

From memory the new() constraint makes the fancy list stuff possible, so it's likely hard to remove (but feel free to try it out and send a PR).

I usually fix this type of problem with ObjectMother - both in terms of getting a default company that makes sense and in terms of only allowing a tax calculator to be created with a company specified.

**Comment by robdmoore** [comment]
Although, in that example I'm not sure tax calculator is the sort of thing that you would want to have a builder for, but I realise it may have been a contrived example or I may be misunderstanding the purpose of that class :)

**Comment by robdmoore** [comment]
Closing for now, but as per above feel free to see if it's possible to remove (I'm pretty sure it's not sorry).
