### ISSUE TITLE
"Doesn't not matter" - typo on wiki page

### ISSUE THREAD

**Issue by grzesiek-galezowski** [TestStack/TestStack.Dossier#45]
Hi, there seems to be a typo on the following page: http://dossier.teststack.net/docs/anonymous-values-and-equivalence-classes

It says: " stealing cognitive load from the test reader while they figure out the value in fact doesn't not matter." and I believe it should be "stealing cognitive load from the test reader while they figure out the value in fact does not matter." or " stealing cognitive load from the test reader while they figure out the value in fact doesn't matter.". I am not a native speaker, though.

**Comment by robdmoore** [comment]
Good pick up. That sentence was plain awkward!

All fixed now :)

Cheers
