### ISSUE TITLE
Calling TestDataBuilder.CreateListOfSize() when the builder have a constructor calls the constructor with one extra call

### ISSUE THREAD

**Issue by stecydube** [TestStack/TestStack.Dossier#51]
Given this POCO class:

``` c#
public class Data
{
    public string Text {get;set;}
}
```

and this custom builder for the POCO class:

``` c#
public class DataBuilder : TestDataBuilder<Data, DataBuilder>
{
    public DataBuilder ()
    {
        var builder = Set (x => x.Text, "Data!!!");
        if (builder == null)
            throw new Exception ("Should not happen !?!!");
    }
}
```

The calling site is:

``` c#
IList<Data> dataList = DataBuilder.CreateListOfSize (1).BuildList ():
```

The exception gets thrown in the DataBuilder constructor since Set() returns null.

I found out that there were two calls to the constructor, the first one is for the proxy generated by CastleWindsor and the second is for the actual instance.

**Comment by robdmoore** [comment]
Given the ctor has `return this as TBuilder` in the `Set` method I can understand if the proxy object doesn't cast to `TBuilder` that it would come back as null.

Does this cause a problem for you? Do you need to chain set calls in the ctor?

**Comment by stecydube** [comment]
I can live with the fact that chaining is not working. It's only a matter of "unchaining" the calls.

However, is it normal that there are two constructor calls when creating a list of 1 item ?
The first constructor call seems to do nothing for the list, however I could not find a way to detect this first call.

**Comment by robdmoore** [comment]
It does make sense yeah,
It's to do with how castle dynamic proxy works (which is what I use behind the scenes to get the "magic" syntax).

https://github.com/castleproject/Core/blob/master/docs/dynamicproxy.md

Is it safe to close this issue or are there any problems this is causing you that we can explore?

**Comment by stecydube** [comment]
Well, the issue remains...
There are two constructor calls and I cannot filter the first one. It seems to me that the first call is extraneous.

**Comment by robdmoore** [comment]
Constructor calls aren't virtual so the proxy can't help but to call it. Normally this isn't an issue since the constructor shouldn't have any side effects.

What problem is the second constructor call giving you if you don't use chaining?

**Comment by stecydube** [comment]
I am under the impression that the first constructor call with all the Set() calls, not chained of course, would have side-effects. Does it do something to the internal structures or is it a no-op?

**Comment by robdmoore** [comment]
Set() etc. Only do things to that individual object so it should be fine :)

**Comment by stecydube** [comment]
Even if I call GetChildBuilder(), no side-effects ?
For now I hacked my way using this code:
```c#
if (GetType ().Namespace.Contains ("Castle"))
    return;
```

**Comment by robdmoore** [comment]
Yep, `GetChildBuilder` just returns another object. Should be fine.

**Comment by stecydube** [comment]
I'm thinking... Could you add a method callable from the constructor to perform a check similar to the one I've provided?
This way it will isolate any change of container in the future.

**Comment by robdmoore** [comment]
Feel free to contribute one in a PR :)

**Comment by robdmoore** [comment]
Closing this issue.

Feel free to contribute a PR with your suggestion though :)
