### ISSUE TITLE
Use builder in for constructor parameter

### ISSUE THREAD

**Issue by LockTar** [TestStack/TestStack.Dossier#56]
Hi,

I have a question about builders. I'm new with your project but I can't find any sample on how to do this.

I have an object called `Project`. It has a public constructor with a few parameters. One of the properties is a `List<AddMemberCommand>`. How can I use a builder for this parameter?

I've tried the generic builder and a custom builder but can't figure it out. Can you help me? 

The `AddMemberCommand` has also an object in the constructor.

    public class Project
    {
    	public Guid Id { get; private set; }
    
    	public string Name { get; private set; }
    
    	private Project() { }
    
    	public Project(string name, List<AddMemberCommand> teamMembers)
    	{
    		Id = Guid.NewGuid();
    		Name = name;
    		//teamMembers.ForEach(AddMember);
    	}
    }

    public class ProjectBuilder : TestDataBuilder<Project, ProjectBuilder>
    {
    	public virtual ProjectBuilder WithName(string name)
    	{
    		return Set(x => x.Name, name);
    	}
    
    	protected override Project BuildObject()
    	{
    		return new Project(
    		  Get(x => x.Name),
    		  new Builder<AddMemberCommand>()
    		);
    	}
    }

    public class AddMemberCommand
    {
    	public Member Member { get; private set; }
        
    	public AddMemberCommand(Member member)
    	{
    		if (member == null)
    		{
    			throw new ArgumentNullException(nameof(member));
    		}
    
    		Member = member;
    	}
    }

Thanks

**Comment by robdmoore** [comment]
Hi,

What you had won't compile since you are expecting a list of `AddMemberCommand`, you'd want your `BuildObject` to be more like:

```c#
    protected override Project BuildObject()
    {
        return new Project(
          Get(x => x.Name),
          new Builder<AddMemberCommand>().CreateListOfSize(3).Build()
        );
    }
```

If you then wanted to control the `Members` that are in the project you might want to do something like:

```c#

public class MemberBuilder : TestDataBuilder<Member, MemberBuilder>
{
    public virtual MemberBuilder WithName(string name)
    {
        return Set(x => x.Name, name);
    }

    protected override Member BuildObject()
    {
        return new Member(
          Get(x => x.Name),
          ...
        );
    }
}

public class ProjectBuilder : TestDataBuilder<Project, ProjectBuilder>
{
    private List<AddMemberCommand> _members = new List<AddMemberCommand>();

    public virtual ProjectBuilder WithName(string name)
    {
        return Set(x => x.Name, name);
    }

    public virtual ProjectBuilder WithMember(Func<MemberBuilder, MemberBuilder> modifier = null)
    {
        _members.Add(new AddMemberCommand(GetChildBuilder(modifier).Build()));
        return this;
    }

    protected override Project BuildObject()
    {
        return new Project(
          Get(x => x.Name),
          _members
        );
    }
}

...

var project = new ProjectBuilder()
    .WithName("My Project")
    .WithMember(m => m.WithName("Member 1"))
    .WithMember(m => m.WithName("Member 2"))
    .Build();
```

HTH

**Comment by LockTar** [comment]
I changed my code to this:

    public class ProjectBuilder : TestDataBuilder<Project, ProjectBuilder>
    {
    	private List<AddTeamMemberCommand> _members;
    	private bool _membersAreSet;
    
    	public virtual ProjectBuilder WithName(string name)
    	{
    		return Set(x => x.Name, name);
    	}
    
    	public virtual ProjectBuilder WithTeamMembers(List<AddTeamMemberCommand> members)
    	{
    		_membersAreSet = true;
    		_members = members;
    		return this;
    	}
    
    	protected override Project BuildObject()
    	{
    		if (!_membersAreSet)
    		{
    			_members = AddTeamMemberCommandBuilder.CreateListOfSize(1).All().WithHourlyRate(null);
    		}
    
    		return new Project(
    		  Get(x => x.Name),
    		  _members,
    		);
    	}
    }


        public class AddTeamMemberCommandBuilder : TestDataBuilder<AddTeamMemberCommand, AddTeamMemberCommandBuilder>
    {
    	private bool _memberIsSet;
    
    	public virtual AddTeamMemberCommandBuilder WithMember(Member member)
    	{
    		_memberIsSet = true;
    		return Set(x => x.Member, member);
    	}
    
    	public virtual AddTeamMemberCommandBuilder WithHourlyRate(decimal? hourlyRate)
    	{
    		return Set(x => x.HourlyRate, hourlyRate);
    	}
    	
    	protected override AddTeamMemberCommand BuildObject()
    	{
    		if (!_memberIsSet)
    		{
    			Set(x => x.Member, Builder<Member>.CreateNew());
    		}
    		
    		return new AddTeamMemberCommand(
    			Get(x => x.Member),
    			Get(x => x.HourlyRate)
    		);
    	}
    }


Is this a good flexible way to use the builders? In this way I can use the `ProjectBuilder` like this: 

    [Fact]
    public void Given_AProjectWith1Member_When_AddAMemberWithHourlyRateToTheTeam_Then_TeamShouldHave2MembersWithAllProjectHourlyRate()
    {
    	const int hourlyRateOriginalMembers = 40;
    	const int hourlyRateNewMember = 50;
    	var originalProjectMembers = AddTeamMemberCommandBuilder.CreateListOfSize(1).All().WithHourlyRate(hourlyRateOriginalMembers).BuildList().ToList();
    	var project = new ProjectBuilder().WithInvoiceMethod(InvoiceMethod.PersonHourlyRate).WithTeamMembers(originalProjectMembers).Build();
    
    	var command = new AddTeamMemberCommandBuilder().WithHourlyRate(hourlyRateNewMember).Build();
    	project.AddMember(command);
    
    	project.TeamMembers.ShouldNotBeNull();
    	project.TeamMembers.Count.ShouldBe(2);
    	project.TeamMembers.All(m => m.HourlyRate.HasValue).ShouldBeTrue();
    	project.TeamMembers[0].HourlyRate.ShouldBe(hourlyRateOriginalMembers);
    	project.TeamMembers[1].HourlyRate.ShouldBe(hourlyRateNewMember);
    }

**Comment by robdmoore** [comment]
Looks reasonable to me. There were a few subtleties around the ChildBuilder stuff that potentially made my example terser, but either way works :) glad you found a way that worked!

**Comment by LockTar** [comment]
I'm trying your solution but I can't get it to work. I get the following compile error on the `GetChildBuilder` in the `WithMember` function.

> The type arguments for method 'TestDataBuilder<Project, ProjectBuilder>.GetChildBuilder<TChildObject, TChildBuilder>(Func<TChildBuilder, TChildBuilder>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

Any suggestion?

**Comment by LockTar** [comment]
Found the right syntax for this problem:
```C#
public virtual ProjectBuilder WithMember(Func<MemberBuilder, MemberBuilder> modifier = null)
{
    _members.Add(new AddTeamMemberCommand(GetChildBuilder<Member, MemberBuilder>(modifier ?? (builder => builder)).Build()));
    return this;
}
```

**Comment by robdmoore** [comment]
Good to hear :)
