### ISSUE TITLE
Pick is missing in nuget  TestStack.Dossier 3.2.1

### ISSUE THREAD

**Issue by scar80** [TestStack/TestStack.Dossier#58]
Hi,
I can see that Pick functionality was committed few months ago but it looks like it is not available in nuget version 3.2.1. Could you please verify it?

> 
The type or namespace name 'Pick' does not exist in the namespace 'TestStack.Dossier.DataSources' (are you missing an assembly reference?)	
The type or namespace name 'Picking' does not exist in the namespace 'TestStack.Dossier.DataSources' (are you missing an assembly reference?)

**Comment by robdmoore** [comment]
Is this the stuff you added @mwhelan?

I can't remember where we got to, but from memory we are waiting for me in some capacity?

**Comment by mwhelan** [comment]
Yes, Pick was something I added.

**Comment by scar80** [comment]
So what is the status here? Will you create new nuget?

**Comment by robdmoore** [comment]
I just published 3.3 :)

HTH
