### ISSUE TITLE
Building lists of relational database entities

### ISSUE THREAD

**Issue by kindjames** [TestStack/TestStack.Dossier#59]
To give an example, I would like to build the following database entities for my tests:

```
public class Driver
{
  public Guid Id { get; set; }
  public IEnumerable<Card> Cards { get; set; }
}

public class Card
{
  public string RFID { get set; }
  public Driver Owner { get;set; }
}
```

I have created Builders for both entities:

```
var driver = new DriverBuilder()
    .WithId(...)
    .Build();

var card = new CardBuilder()
    .WithRFID(...)
    .WithDriver(driver)
    .Build();
```

The WithDriver() method is as follows:

```
public virtual CardBuilder WithDriver(Driver driver)
{
    return Set(x => x.Driver, driver);
}
```

This correctly sets the Driver navigation property on the Card being built, however, how do I also add the Card to-be-built to the Cards property on the Driver??

I know I must be missing something because I feel like I'm chasing my tail!

Thank you

**Comment by robdmoore** [comment]
2 ways I can think of:

1) rely on the orm to do it; depending on how they are mapped and the orm, you may be able to only add one side of the relationship and then it will automatically figure out the other side(or after saving you re-query the entities to get a fully populated version).
2) In the BuildObject call within the CardBuilder after the card is created you could add the card to the list in the driver. Obviously that won't work if it's an IEnumerable, but hopefully you get the idea.

btw, one way to make this terser is to use the GetChildBuilder method within the WithDriver method in CardBuilder as per the bottom of http://dossier.teststack.net/docs/basic-builder-methods.

**Comment by kindjames** [comment]
Thanks Rob. 

Unfortunately for the tests I want to write, I can't rely on the ORM.

I like the GetChildBuilder method - I couldn't figure that out before.

If I wanted to use it to add items to a list, e.g. 

```
var driver = new DriverBuilder()
    .WithId(...)
    .WithCard(c => c.WithRFID("ABC"))
    .WithCard(c => c.WithRFID("DEF"))
    .Build();
```

How would I go about implementing the WithCard() method? I have the following but obviously I can't set a List for a single item.... I'm wondering if there's a way to 'add' to the Cards list?

```
public virtual DriverBuilder WithCard(Func<CardBuilder, CardBuilder> modifier = null)
{
    return Set(x => x.Cards, GetChildBuilder<Card, CardBuilder>(modifier));
}
```

**Comment by kindjames** [comment]
Perhaps something like this?

```
public virtual DriverBuilder WithCard(Func<CardBuilder, CardBuilder> modifier = null)
{
    var cards = Get(x => x.Cards);

    cards.Add(GetChildBuilder<Card, CardBuilder>(modifier));

    return Set(x => x.Cards, cards);
}
```

**Comment by robdmoore** [comment]
I'd just keep track of a list as a private field that I add to in the WithCard method and you could Set the reference in the builder constructor

**Comment by kindjames** [comment]
Agreed. I've now implemented as per your suggestion. Thanks for you help! :)
