### ISSUE TITLE
Looking for example of a builder that builds an object with a collections of child objects

### ISSUE THREAD

**Issue by jimmcslim** [TestStack/TestStack.Dossier#66]
I'm trying to use Dossier to build an object that maintains a collection of related objects, e.g. imagine an `Order` that encapsulates zero, one, or many `OrderLine` instances.

````
public class Order {
  public string OrderReference { get; set; }
  public List<OrderLine> OrderLines { get; } => new List<OrderLine>();
}

public class OrderLine {
  public string Sku { get; set; }
  public int Quantity { get; set; }
}
````

I'm assuming in this case I need to implement `BuildObject` manually for my `OrderBuilder`, in order to do a `Get(x => x.OrderLines)` and then call `.AddRange()` on the `OrderLines` property of the `Order` that I construct... however I'm getting an `InvalidCastException` trying to get from `OrderLine[]` to `List<OrderLine>`.

I could put up a full repro if that would help.

**Comment by mwhelan** [comment]
Hi @jimmcslim 

Yes, by default the [TestDataBuilder uses the PublicPropertySettersFactory](https://github.com/TestStack/TestStack.Dossier/blob/3ca2e7579587932be10c846c114a60a8035b0e6a/TestStack.Dossier/TestDataBuilder.cs#L79) and so will not attempt to set the read-only property. 

This example will work:

    public class Order
    {
        public string OrderReference { get; set; }
        public List<OrderLine> OrderLines { get; } = new List<OrderLine>();
    }

    public class OrderLine
    {
        public string Sku { get; set; }
        public int Quantity { get; set; }
    }

    public class OrderBuilder : TestDataBuilder<Order, OrderBuilder>
    {
        protected override Order BuildObject()
        {
            var order = base.BuildObject();
            order.OrderLines
                .AddRange(Get(x => x.OrderLines));
            return order;
        }
    }

    public class TestFixture
    {
        [Test]
        public void Test()
        {
            var orderLines = Builder<OrderLine>
                .CreateListOfSize(3)
                .BuildList()
                .ToList();

            Order order = new OrderBuilder()
                .Set(x => x.OrderLines, orderLines);

            order.OrderLines.Should().HaveCount(3);
        }
    } 

The invalidcastexception is just the mismatch with IList and List, which the ToList method on setting the orderLines variable resolves in the example.

**Comment by jimmcslim** [comment]
Excellent, thanks for that!
